// Generated by CoffeeScript 1.7.1
(function() {
  var $;

  $ = {};

  $.remove = function(array, element) {
    var index, _ref;
    if ((index = array.indexOf(element)) > -1) {
      [].splice.apply(array, [index, index - index + 1].concat(_ref = [])), _ref;
      return element;
    } else {
      return null;
    }
  };

  $.uniq = function(array, hash) {
    var element, key, uniques, _i, _j, _len, _len1, _ref, _results;
    if (hash == null) {
      hash = function(object) {
        return object.toString();
      };
    }
    uniques = {};
    for (_i = 0, _len = array.length; _i < _len; _i++) {
      element = array[_i];
      uniques[hash(element)] = element;
    }
    _ref = Object.keys(uniques);
    _results = [];
    for (_j = 0, _len1 = _ref.length; _j < _len1; _j++) {
      key = _ref[_j];
      _results.push(uniques[key]);
    }
    return _results;
  };

  $.shuffle = function(array) {
    var copy, i, j, _i, _ref, _ref1;
    copy = array.slice(0);
    if (copy.length <= 1) {
      return copy;
    }
    for (i = _i = _ref = copy.length - 1; _ref <= 1 ? _i <= 1 : _i >= 1; i = _ref <= 1 ? ++_i : --_i) {
      j = Math.floor(Math.random() * (i + 1));
      _ref1 = [copy[j], copy[i]], copy[i] = _ref1[0], copy[j] = _ref1[1];
    }
    return copy;
  };

  module.exports = $;

}).call(this);
