// Generated by CoffeeScript 1.7.1
(function() {
  var $;

  $ = {};

  $.md5 = function(string) {
    var Crypto;
    Crypto = require("crypto");
    return Crypto.createHash('md5').update(string, 'utf-8').digest("hex");
  };

  $.base64 = function(string) {
    var Crypto;
    Crypto = require("crypto");
    return new Buffer(string).toString('base64');
  };

  module.exports = $;

}).call(this);
