// Generated by CoffeeScript 1.7.1
(function() {
  var $;

  $ = {};

  $.exists = function(path) {
    var FileSystem;
    FileSystem = require("fs");
    return FileSystem.existsSync(path);
  };

  $.read = function(path) {
    var FileSystem;
    FileSystem = require("fs");
    return FileSystem.readFileSync(path, 'utf-8');
  };

  $.readdir = function(path) {
    var FileSystem;
    FileSystem = require("fs");
    return FileSystem.readdirSync(path);
  };

  $.stat = function(path) {
    var FileSystem;
    FileSystem = require("fs");
    return FileSystem.statSync(path);
  };

  $.write = function(path, content) {
    var FileSystem;
    FileSystem = require("fs");
    return FileSystem.writeFileSync(path, content);
  };

  $.chdir = function(dir, fn) {
    var cwd, rval;
    cwd = process.cwd();
    process.chdir(dir);
    rval = fn();
    process.chdir(cwd);
    return rval;
  };

  $.rm = function(path) {
    var FileSystem;
    FileSystem = require("fs");
    return FileSystem.unlinkSync(path);
  };

  $.rmdir = function(path) {
    var FileSystem;
    FileSystem = require("fs");
    return FileSystem.rmdirSync(path);
  };

  module.exports = $;

}).call(this);
