// Generated by CoffeeScript 1.7.1
(function() {
  var $, basename, filename, include, readdir, _i, _len, _module, _ref;

  $ = {};

  $.w = function(string) {
    return string.trim().split(/\s+/);
  };

  $.to = function(to, from) {
    if (from instanceof to) {
      return from;
    } else {
      return new to(from);
    }
  };

  $.abort = function() {
    return process.exit(-1);
  };

  $.memoize = function(fn, hash) {
    var memo;
    if (hash == null) {
      hash = function(object) {
        return object.toString();
      };
    }
    memo = {};
    return function(thing) {
      var _name;
      return memo[_name = hash(thing)] != null ? memo[_name] : memo[_name] = fn(thing);
    };
  };


  /* timer */

  $.timer = function(wait, action) {
    var id;
    id = setTimeout(action, wait);
    return function() {
      return clearTimeout(id);
    };
  };

  basename = require("path").basename;

  readdir = require("./fs").readdir;

  include = require("./object").include;

  _ref = readdir(__dirname);
  for (_i = 0, _len = _ref.length; _i < _len; _i++) {
    filename = _ref[_i];
    _module = basename(filename, ".coffee");
    if (_module !== "index") {
      include($, require("./" + _module));
    }
  }

  module.exports = $;

}).call(this);
