// Generated by CoffeeScript 1.7.1
(function() {
  var $, include, type,
    __slice = [].slice;

  $ = {};

  type = require("./type");

  $.include = include = function() {
    var key, mixin, mixins, object, value, _i, _len;
    object = arguments[0], mixins = 2 <= arguments.length ? __slice.call(arguments, 1) : [];
    for (_i = 0, _len = mixins.length; _i < _len; _i++) {
      mixin = mixins[_i];
      for (key in mixin) {
        value = mixin[key];
        object[key] = value;
      }
    }
    return object;
  };

  $.Property = {
    property: (function() {
      var defaults;
      defaults = {
        enumerable: true,
        configurable: true
      };
      return function(properties) {
        var key, value, _results;
        _results = [];
        for (key in properties) {
          value = properties[key];
          include(value, defaults);
          _results.push(Object.defineProperty(this.prototype, key, value));
        }
        return _results;
      };
    })()
  };

  $.delegate = function(from, to) {
    var name, value, _results;
    _results = [];
    for (name in to) {
      value = to[name];
      if ((type(value)) === "function") {
        _results.push((function(value) {
          return from[name] = function() {
            var args;
            args = 1 <= arguments.length ? __slice.call(arguments, 0) : [];
            return value.call.apply(value, [to].concat(__slice.call(args)));
          };
        })(value));
      }
    }
    return _results;
  };

  $.merge = function() {
    var destination, k, object, objects, v, _i, _len;
    objects = 1 <= arguments.length ? __slice.call(arguments, 0) : [];
    destination = {};
    for (_i = 0, _len = objects.length; _i < _len; _i++) {
      object = objects[_i];
      for (k in object) {
        v = object[k];
        destination[k] = v;
      }
    }
    return destination;
  };

  $.clone = function(object) {
    var clone, flags, key;
    if ((object == null) || typeof object !== 'object') {
      return object;
    }
    if (object instanceof Date) {
      return new Date(obj.getTime());
    }
    if (object instanceof RegExp) {
      flags = '';
      if (object.global != null) {
        flags += 'g';
      }
      if (object.ignoreCase != null) {
        flags += 'i';
      }
      if (object.multiline != null) {
        flags += 'm';
      }
      if (object.sticky != null) {
        flags += 'y';
      }
      return new RegExp(object.source, flags);
    }
    clone = new object.constructor();
    for (key in object) {
      clone[key] = $.clone(object[key]);
    }
    return clone;
  };

  module.exports = $;

}).call(this);
