// Generated by CoffeeScript 1.7.1
(function() {
  var $;

  $ = {};

  $.capitalize = function(string) {
    return string[0].toUpperCase() + string.slice(1);
  };

  $.titleCase = function(string) {
    return string.toLowerCase().replace(/^(\w)|\W(\w)/g, function(char) {
      return char.toUpperCase();
    });
  };

  $.camelCase = $.camel_case = function(string) {
    return string.toLowerCase().replace(/(\W+\w)/g, function(string) {
      return string.trim().toUpperCase();
    });
  };

  $.underscored = function(string) {
    return $.plainText(string).replace(/\W+/g, "_");
  };

  $.dashed = function(string) {
    return $.plainText(string).replace(/\W+/g, "-");
  };

  $.plainText = $.plain_text = function(string) {
    return string.replace(/^[A-Z]/g, function(c) {
      return c.toLowerCase();
    }).replace(/[A-Z]/g, function(c) {
      return " " + (c.toLowerCase());
    }).replace(/\W+/g, " ");
  };

  $.htmlEscape = $.html_escape = (function() {
    var entities, map, re;
    map = {
      "&": "&amp;",
      "<": "&lt;",
      ">": "&gt;",
      '"': '&quot;',
      "'": '&#39;',
      "/": '&#x2F;'
    };
    entities = Object.keys(map);
    re = new RegExp("" + (entities.join('|')), "g");
    return function(string) {
      return string.replace(re, function(s) {
        return map[s];
      });
    };
  })();

  module.exports = $;

}).call(this);
