// Generated by CoffeeScript 1.7.1
(function() {
  var classToType, classes, name, _i, _len;

  classes = ["Boolean", "Number", "String", "Function", "Array", "Date", "RegExp"];

  classToType = new Object;

  for (_i = 0, _len = classes.length; _i < _len; _i++) {
    name = classes[_i];
    classToType["[object " + name + "]"] = name.toLowerCase();
  }

  module.exports = {
    type: function(object) {
      var myClass;
      if (object === void 0) {
        return "undefined";
      }
      if (object === null) {
        return "null";
      }
      myClass = Object.prototype.toString.call(object);
      if (myClass in classToType) {
        return classToType[myClass];
      } else {
        return "object";
      }
    }
  };

}).call(this);
