{include} = require "fairmont-helpers"
include module.exports, require "fairmont-core"
include module.exports, require "fairmont-helpers"
include module.exports, require "fairmont-multimethods"
include module.exports, require "fairmont-reactive"
include module.exports, require "fairmont-process"
include module.exports, require "fairmont-filesystem"
